services:

  parking-stats-service-db:
    image: postgres:17.4-alpine
    container_name: parking-stats-service-db
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_EPORT}:${DB_PORT}
    networks:
      - app-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 20

  parking-stats-service:
    image: parking-stats-service:0.0.1
    container_name: parking-stats-service
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - ${APP_EPORT}:${APP_PORT}
    networks:
      - app-net
    depends_on:
      parking-stats-service-db:
        condition: service_healthy

networks:
  app-net:
    driver: bridge

volumes:
  pgdata: