spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:${DB_BASE:postgresql}://${DB_SERVER:localhost}:${DB_PORT:5433}/${DB_NAME:parking_stats_service_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

logging:
  level:
    org.springframework.transaction: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.gitverse.testcakes.parkings: debug